### ISSUE TITLE
Message type format - string or integer?

### ISSUE THREAD

**Issue by janj-epam** [LykkeBusiness/openvasp-message-samples#2]
According to the whitepaper, message type is a String. So in JSON, for example, the SessionRequest msg type would be like this:

"msg" {
    "type": "110",
    ...
}

However, the provided messages encode it like this:

"msg" {
    "type": 110,
    ...
}

i.e. as a number (without quotes).

Should we follow the whitepaper or the provided messages?

**Comment by nikagamkrelidze** [comment]
fixed in latest client/host.
